### ISSUE TITLE
Missing requirements.txt file and Python version specification

### ISSUE THREAD

**Issue by Junhua9981** [sian-wusidi/spatialcooccurrence#1]
Hi,

I'm trying to use your model to run experiments on my data. During the installation and configuration process, I noticed that the original repository lacks a requirements.txt file, which caused me some problems while setting up the environment.

To ensure smooth installation and use of your model for all users, I suggest you consider adding a requirements.txt file or the environments.yml (if you are using conda) to the repository. 

Thanks for your hard work and excellent contribution. I look forward to seeing the resolution of this issue!

**Comment by sian-wusidi** [comment]
Hi,
Thanks for your suggestion. We have attach the environments.yml. You can import it in Anaconda.
Some minor bugs have also been fixed.
